[package]
name = "KeyVisual"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.28.7"
pixels = "0.12.1"
fontdue = "0.9.3"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"